name: generate feeds show off

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run script
        env:
          MINIFLUX_API_KEY: ${{ secrets.MINIFLUX_API_KEY }}
        run: python generate_readme.py

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: update branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}